# Add new language here

LANG_JSON = {
    "en": {
        "app_title": "Mini Nano GPT",
        "language_label": "Language",
        "data_process_tab": "Data Processing",
        "train_tab": "Training",
        "infer_tab": "Inference",

        "dp_paste_text": "Paste Text",
        "dp_txt_dir": "TXT Directory (Optional)",
        "dp_raw_dir": "Raw Data Directory",
        "dp_processed_dir": "Processed Data Directory",
        "dp_train_split": "Training Split Ratio",
        "dp_no_val_set": "Do not use validation set",
        "dp_use_gpt2_tokenizer": "Use GPT-2 Tokenizer",
        "dp_num_proc": "Number of Processes",
        "dp_start_btn": "Start Processing",
        "dp_result": "Processing Result",

        "train_params_title": "Training Parameters",
        "train_data_dir": "Data Directory (where train.bin/val.bin)",
        "train_out_dir": "Output Directory",
        "train_eval_interval": "Plot Interval",
        "train_log_interval": "Logging Interval",
        "train_num_eval_seeds": "Number of Evaluation Seeds",
        "train_save_best_val_ckpt": "Save Best Val Loss Checkpoint",
        "train_init_from": "Initialization Source",
        "train_gas": "Gradient Accumulation Steps",
        "train_batch_size": "Batch Size",
        "train_block_size": "Block Size",
        "train_n_layer": "Number of Layers",
        "train_n_head": "Number of Attention Heads",
        "train_n_embd": "Embedding Dimension",
        "train_dropout": "Dropout Rate",
        "train_bias": "Use Bias",
        "train_lr": "Learning Rate",
        "train_max_iters": "Maximum Iterations",
        "train_weight_decay": "Weight Decay",
        "train_beta1": "Beta 1",
        "train_beta2": "Beta 2",
        "train_lr_scheduler": "Learning Rate Scheduler",
        "train_warmup_iters": "Warmup Iterations",
        "train_lr_decay_iters": "Learning Rate Decay Iterations",
        "train_min_lr": "Minimum Learning Rate",
        "train_backend": "Backend",
        "train_device": "Device",
        "train_dtype": "Data Type",
        "train_compile_model": "Compile Model",
        "train_start_btn": "Start Training",
        "train_log": "Training Log",
        "train_plot": "Loss Curve",
        "train_seed": "Seed",
        "train_save_interval": "Save Interval (Steps)",

        "inf_out_dir": "Model Directory (ckpt.pt)",
        "inf_prompt": "Prompt",
        "inf_num_samples": "Number of Samples",
        "inf_max_new_tokens": "Maximum New Tokens",
        "inf_temperature": "Temperature",
        "inf_top_k": "Top K",
        "inf_start_btn": "Generate",
        "inf_result": "Generation Result",
        "inf_seed": "Seed",
        "stop_btn": "Stop Training"
    },
    "zh": {
        "app_title": "Mini Nano GPT",
        "language_label": "语言",
        "data_process_tab": "数据处理",
        "train_tab": "训练",
        "infer_tab": "推理",

        "dp_paste_text": "粘贴文本",
        "dp_txt_dir": "TXT文件目录（可选）",
        "dp_raw_dir": "原始数据目录",
        "dp_processed_dir": "处理后数据目录",
        "dp_train_split": "训练集比例 (Training Split Ratio)",
        "dp_no_val_set": "暂不需要验证集",
        "dp_use_gpt2_tokenizer": "使用 GPT-2 分词器 (Use GPT-2 Tokenizer)",
        "dp_num_proc": "进程数 (Number of processes)",
        "dp_start_btn": "开始处理",
        "dp_result": "处理结果",

        "train_params_title": "训练参数 (Training Parameters)",
        "train_data_dir": "数据目录（包含 train.bin/val.bin）",
        "train_out_dir": "输出目录",
        "train_eval_interval": "评估间隔 (Plot Interval)",
        "train_log_interval": "日志间隔 (Logging Interval)",
        "train_num_eval_seeds": "评估种子数量 (Number of Evaluation Seeds)",
        "train_save_best_val_ckpt": "保存验证损失最佳点 (Save Best Val Loss Checkpoint)",
        "train_init_from": "初始化方式 (Initialization Source)",
        "train_gas": "梯度累积步数 (Gradient Accumulation Steps)",
        "train_batch_size": "批量大小 (Batch Size)",
        "train_block_size": "块/上下文大小 (Block Size)",
        "train_n_layer": "层数 (Number of Layers)",
        "train_n_head": "头数 (Number of Attention Heads)",
        "train_n_embd": "嵌入维度 (Embedding Dimension)",
        "train_dropout": "丢弃率 (Dropout Rate)",
        "train_bias": "是否使用偏置？ (Use Bias)",
        "train_lr": "学习率 (Learning Rate)",
        "train_max_iters": "最大迭代次数 (Maximum Iterations)",
        "train_weight_decay": "权重衰减 (Weight Decay)",
        "train_beta1": "β1 (Beta 1)",
        "train_beta2": "β2 (Beta 2)",
        "train_lr_scheduler": "学习率调度器 (Learning Rate Scheduler)",
        "train_warmup_iters": "预热迭代次数 (Warmup Iterations)",
        "train_lr_decay_iters": "学习率衰减迭代次数 (Learning Rate Decay Iterations)",
        "train_min_lr": "最小学习率 (Minimum Learning Rate)",
        "train_backend": "后端 (Backend)",
        "train_device": "设备 (Device)",
        "train_dtype": "数据类型 (Data Type)",
        "train_compile_model": "编译模型 (Compile Model)",
        "train_start_btn": "开始训练",
        "train_log": "训练日志 (Training Log)",
        "train_plot": "损失曲线 (Loss Curve)",
        "train_seed": "种子 (Seed)",
        "train_save_interval": "保存间隔 (Save Interval)",

        "inf_out_dir": "模型目录（ckpt.pt）",
        "inf_prompt": "提示词 (Prompt)",
        "inf_num_samples": "生成样本数 (Number of Samples)",
        "inf_max_new_tokens": "最多生成标记数 (Maximum New Tokens)",
        "inf_temperature": "温度 (Temperature)",
        "inf_top_k": "TOP K",
        "inf_start_btn": "开始生成",
        "inf_result": "生成结果",
        "inf_seed": "种子 (Seed)",
        "stop_btn": "停止训练"
    }
}
